import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function GameOver({ winner, leaderboard, myPlayer, onPlayAgain }) {
    const medals = ['🥇', '🥈', '🥉'];
    return (_jsx("div", { style: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100, backdropFilter: 'blur(6px)' }, children: _jsxs("div", { style: { background: '#1a1a2e', borderRadius: '24px', padding: '36px', width: '90%', maxWidth: '460px', border: '2px solid #4f46e5', textAlign: 'center' }, children: [_jsx("div", { style: { fontSize: '48px', marginBottom: '8px' }, children: "\uD83C\uDF89" }), _jsx("h1", { style: { fontFamily: 'Fredoka One', fontSize: '36px', color: '#a5b4fc', marginBottom: '20px' }, children: "Game Over!" }), winner && (_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: '16px', background: '#0f0f1a', borderRadius: '16px', padding: '16px 24px', marginBottom: '20px', border: '1px solid #f59e0b44' }, children: [_jsx("div", { style: { width: 56, height: 56, borderRadius: '50%', background: winner.avatar, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '22px', fontWeight: 800, color: '#fff' }, children: winner.name[0].toUpperCase() }), _jsxs("div", { children: [_jsx("div", { style: { fontWeight: 800, fontSize: '22px' }, children: winner.name }), _jsxs("div", { style: { color: '#f59e0b', fontWeight: 700 }, children: [winner.score, " points \uD83C\uDFC6"] })] })] })), _jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '24px' }, children: leaderboard.map((p, i) => (_jsxs("div", { style: {
                            display: 'flex', alignItems: 'center', gap: '10px', padding: '12px', borderRadius: '10px',
                            background: p.id === myPlayer.id ? '#1e1e40' : '#0f0f1a',
                            borderLeft: i === 0 ? '3px solid #f59e0b' : '3px solid transparent',
                        }, children: [_jsx("span", { style: { fontSize: '20px', minWidth: '30px' }, children: medals[i] || `#${i + 1}` }), _jsx("div", { style: { width: 32, height: 32, borderRadius: '50%', background: p.avatar, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '13px', fontWeight: 800, color: '#fff' }, children: p.name[0].toUpperCase() }), _jsx("span", { style: { flex: 1, fontWeight: 700 }, children: p.name }), p.id === myPlayer.id && _jsx("span", { style: { padding: '2px 8px', borderRadius: '99px', background: '#4f46e5', color: '#fff', fontSize: '11px', fontWeight: 800 }, children: "You" }), _jsxs("span", { style: { color: '#818cf8', fontWeight: 800 }, children: [p.score, " pts"] })] }, p.id))) }), _jsx("button", { onClick: onPlayAgain, style: { width: '100%', padding: '14px', borderRadius: '12px', border: 'none', background: '#4f46e5', color: '#fff', fontSize: '18px', cursor: 'pointer', fontWeight: 800 }, children: "\uD83C\uDFE0 Back to Home" })] }) }));
}
