import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function PlayerList({ players, myPlayer, phase }) {
    const sorted = [...players].sort((a, b) => b.score - a.score);
    return (_jsxs("div", { style: { display: 'flex', flexDirection: 'column', background: '#1a1a2e', borderRadius: '16px', overflow: 'hidden', border: '1px solid #2d2d4e', height: '100%' }, children: [_jsx("div", { style: { padding: '12px 16px', background: '#0f0f1a', fontWeight: 800, fontSize: '14px', color: '#a5b4fc', borderBottom: '1px solid #2d2d4e' }, children: "\uD83C\uDFC6 Players" }), _jsx("div", { style: { flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '4px', padding: '8px' }, children: sorted.map((p, idx) => (_jsxs("div", { style: {
                        display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 10px', borderRadius: '10px',
                        borderLeft: p.isDrawing ? '3px solid #4f46e5' : '3px solid transparent',
                        background: p.id === myPlayer.id ? '#1e1e3a' : '#0f0f1a',
                    }, children: [_jsxs("span", { style: { color: '#6b7280', fontSize: '12px', fontWeight: 800, minWidth: '20px' }, children: ["#", idx + 1] }), _jsx("div", { style: { width: 32, height: 32, borderRadius: '50%', background: p.avatar, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontSize: '14px', color: '#fff', flexShrink: 0 }, children: p.name[0].toUpperCase() }), _jsxs("div", { style: { flex: 1, minWidth: 0 }, children: [_jsxs("div", { style: { fontWeight: 700, fontSize: '13px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }, children: [p.name, " ", p.id === myPlayer.id && _jsx("span", { style: { color: '#4f46e5', fontSize: '10px' }, children: "\u25CF" })] }), _jsxs("div", { style: { color: '#818cf8', fontSize: '12px', fontWeight: 700 }, children: [p.score, " pts"] })] }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '2px' }, children: [p.isHost && _jsx("span", { children: "\uD83D\uDC51" }), p.isDrawing && phase === 'drawing' && _jsx("span", { children: "\u270F\uFE0F" }), p.hasGuessed && !p.isDrawing && _jsx("span", { children: "\u2705" })] })] }, p.id))) })] }));
}
