import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function Lobby({ players, myPlayer, roomCode, settings, onStartGame }) {
    const copyCode = () => {
        navigator.clipboard.writeText(roomCode);
        alert('Room code copied!');
    };
    return (_jsxs("div", { style: { minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '24px 16px', gap: '20px' }, children: [_jsx("h1", { style: { fontFamily: 'Fredoka One', fontSize: '40px', background: 'linear-gradient(135deg, #818cf8, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }, children: "\uD83C\uDFA8 skribbl" }), _jsxs("div", { style: { display: 'flex', gap: '20px', width: '100%', maxWidth: '800px', flexWrap: 'wrap' }, children: [_jsxs("div", { style: { background: '#1a1a2e', borderRadius: '20px', padding: '24px', flex: 1, minWidth: '280px', border: '1px solid #2d2d4e' }, children: [_jsx("p", { style: { color: '#a5b4fc', fontSize: '13px', fontWeight: 800, textTransform: 'uppercase', marginBottom: '12px' }, children: "Room Code" }), _jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: '12px', background: '#0f0f1a', borderRadius: '12px', padding: '12px 16px', marginBottom: '10px' }, children: [_jsx("span", { style: { fontFamily: 'Fredoka One', fontSize: '32px', letterSpacing: '6px', color: '#818cf8', flex: 1 }, children: roomCode }), _jsx("button", { onClick: copyCode, style: { padding: '8px 14px', borderRadius: '8px', border: 'none', background: '#2d2d4e', color: '#fff', cursor: 'pointer', fontSize: '13px', fontWeight: 700 }, children: "\uD83D\uDCCB Copy" })] }), _jsx("p", { style: { color: '#a5b4fc', fontSize: '13px', fontWeight: 800, textTransform: 'uppercase', margin: '20px 0 12px' }, children: "Settings" }), _jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: '8px' }, children: [
                                    ['👥 Players', `${players.length}/${settings.maxPlayers}`],
                                    ['🔄 Rounds', settings.rounds],
                                    ['⏱ Draw Time', `${settings.drawTime}s`],
                                    ['📝 Word Choices', settings.wordCount],
                                ].map(([label, value]) => (_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', padding: '8px 12px', background: '#0f0f1a', borderRadius: '8px', fontSize: '14px' }, children: [_jsx("span", { children: label }), _jsx("span", { children: value })] }, label))) }), myPlayer.isHost ? (_jsx("button", { onClick: onStartGame, disabled: players.length < 2, style: { width: '100%', padding: '16px', borderRadius: '14px', border: 'none', background: players.length < 2 ? '#1a3a1a' : 'linear-gradient(135deg, #22c55e, #16a34a)', color: '#fff', fontSize: '20px', cursor: players.length < 2 ? 'not-allowed' : 'pointer', marginTop: '20px', fontWeight: 800 }, children: players.length < 2 ? '⏳ Need 2+ players' : '🚀 Start Game!' })) : (_jsx("div", { style: { textAlign: 'center', color: '#6b7280', padding: '16px', marginTop: '16px', background: '#0f0f1a', borderRadius: '10px' }, children: "\u23F3 Waiting for host to start..." }))] }), _jsxs("div", { style: { background: '#1a1a2e', borderRadius: '20px', padding: '24px', flex: 1, minWidth: '280px', border: '1px solid #2d2d4e' }, children: [_jsxs("p", { style: { color: '#a5b4fc', fontSize: '13px', fontWeight: 800, textTransform: 'uppercase', marginBottom: '12px' }, children: ["Players (", players.length, ")"] }), _jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: '10px' }, children: players.map(p => (_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: '12px', padding: '10px', background: '#0f0f1a', borderRadius: '10px' }, children: [_jsx("div", { style: { width: 40, height: 40, borderRadius: '50%', background: p.avatar, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontSize: '16px', color: '#fff' }, children: p.name[0].toUpperCase() }), _jsx("span", { style: { flex: 1, fontWeight: 700 }, children: p.name }), p.id === myPlayer.id && _jsx("span", { style: { padding: '2px 8px', borderRadius: '99px', background: '#4f46e5', color: '#fff', fontSize: '11px', fontWeight: 800 }, children: "You" }), p.isHost && _jsx("span", { style: { fontSize: '16px' }, children: "\uD83D\uDC51" })] }, p.id))) })] })] })] }));
}
